### ISSUE TITLE
Addon no longer works in FF 52.0b1 :-(

### ISSUE THREAD

**Issue by ineuw** [fdgueux/TabsOnBottom#8]
The title says it all. :-(

**Comment by fdgueux** [comment]
Did the 2.0.0 version revolse this issue?

**Comment by ineuw** [comment]
Hi, Currently it works well in Windows 7,  I will post here later the results from Linux mint 18 Sara. I use the same FF version both OS.

**Comment by ineuw** [comment]
Version 2.00 works Ok in Linux Mint 18 (32bit),
